### ISSUE TITLE
MVP and Schema Issues

### ISSUE THREAD

**Issue by OhBall** [keith-io/Songify#1]
### MVP’s: 

- [x] MVP List description is from bluebird 👎 

- [x] In your mvp list, change: “Users can view an index 'if' => 'of' their own playlists”

### Schema:

- [x] In the details of your `users` table, you write that `username` is indexed but not unique. Below the table, you write that it is in fact unique. For email, you say that it is indexed and unique, but neither of those are listed below the table.  

- [x] Songs can be in multiple playlists, so it does not make sense for them to hold a playlist_id. Instead, there should be a joins table.

- [x] How will you group songs from the same album together? What if there are two different albums of the same name?

- [x] You intend to have the ability to follow a playlist for your 6th MVP. Will your backend need anything to accomplish this? 

- [x] For your `likes` table, you have `index on :user_id, unique: true`. This would make it so that a user could only ever like one song.

- [x] Will albums have artwork? If so, then you will most likely want to use AWS. We have resources for how to set that up, but for now a photo_url column would suffice.

**Comment by keith-io** [comment]
+ songs will be grouped by album_id, not title (oops, thanks)
+ I'm actually not sure what the best way to handle likes is, but this time I'm trying a joins table.
